In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
unames = ['user_id', 'gender', 'age', 'occupation', 'zip']
user_df = pd.read_table(
    'ml-1m/users.dat',
    sep='::',
    header=None,
    names=unames,
    engine='python'
)

In [8]:
mnames = ['movie_id', 'title', 'genres']
movies_df = pd.read_table(
    'ml-1m/movies.dat',
    sep='::',
    header=None,
    names=mnames,
    engine='python',
    encoding='latin-1'
)

In [9]:
rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings_df = pd.read_table(
    'ml-1m/ratings.dat',
    sep='::',
    header=None,
    names=rnames,
    engine='python'
)

In [10]:
user_df

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
...       ...    ...  ...         ...    ...
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [11]:
movies_df

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [12]:
ratings_df

         user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
...          ...       ...     ...        ...
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [13]:
df = pd.merge(pd.merge(ratings_df, user_df), movies_df, sort=True)

df

,user_id,movie_id,rating,timestamp,gender,age,occupation,zip,title,genres
0,1,1,5,978824268,F,1,10,48067,Toy Story (1995),Animation|Children's|Comedy
1,6,1,4,978237008,F,50,9,55117,Toy Story (1995),Animation|Children's|Comedy
2,8,1,4,978233496,M,25,12,11413,Toy Story (1995),Animation|Children's|Comedy
3,9,1,5,978225952,M,25,17,61614,Toy Story (1995),Animation|Children's|Comedy
4,10,1,5,978226474,F,35,1,95370,Toy Story (1995),Animation|Children's|Comedy
...,...,...,...,...,...,...,...,...,...,...
1000204,5812,3952,4,992072099,F,25,7,92120,"Contender, The (2000)",Drama|Thriller
1000205,5831,3952,3,986223125,M,25,1,92120,"Contender, The (2000)",Drama|Thriller
1000206,5837,3952,4,1011902656,M,25,7,60607,"Contender, The (2000)",Drama|Thriller
1000207,5927,3952,1,979852537,M,35,14,10003,"Contender, The (2000)",Drama|Thriller
1000208,5998,3952,4,1001781044,M,18,4,61820,"Contender, The (2000)",Drama|Thriller